<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-7MT187F0" failures="1" tests="3" name="javaSusret21.Zadatak2" time="52.318" errors="0" timestamp="2021-01-27T09:52:44 CET" skipped="0">
  <testcase classname="javaSusret21.Zadatak2" name="logIn" time="11.611">
    <failure message="expected [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611861140%7CTidzpBAtN7vL46g7p2F7YFkB6A18FuNeNEpGVEBfPC3%7C5fbb658742b301d6f29951fdfc5c32c2d71c2624ce17c3cdd950ed9fdc202fb2; path=/] but found [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611910318%7CoaxuYaQ51hZp2FpZQScOXCXpHJa67aQwpRqbKaok9yp%7Ca4deb09e70ae1c0ed24792ab1d6588acf31a437181a7605e08379c0a4dde94a2; path=/; domain=cms.demo.katalon.com]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611861140%7CTidzpBAtN7vL46g7p2F7YFkB6A18FuNeNEpGVEBfPC3%7C5fbb658742b301d6f29951fdfc5c32c2d71c2624ce17c3cdd950ed9fdc202fb2; path=/] but found [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611910318%7CoaxuYaQ51hZp2FpZQScOXCXpHJa67aQwpRqbKaok9yp%7Ca4deb09e70ae1c0ed24792ab1d6588acf31a437181a7605e08379c0a4dde94a2; path=/; domain=cms.demo.katalon.com]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at javaSusret21.Zadatak2.logIn(Zadatak2.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logIn -->
  <system-out/>
  <testcase classname="javaSusret21.Zadatak2" name="dodavanjeItemaUKorpu" time="17.234"/>
  <system-out/>
  <testcase classname="javaSusret21.Zadatak2" name="brisanjeItemaIzKorpe" time="23.473"/>
  <system-out/>
</testsuite> <!-- javaSusret21.Zadatak2 -->
